# Generated by Django 5.2.8 on 2025-11-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Référence externe (LigdiCash)'),
        ),
    ]
