# Generated by Django 5.2.6 on 2025-11-13 02:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0003_alter_inscription_apprenant'),
        ('establishments', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('numero_compte', models.CharField(max_length=20, verbose_name='Numéro de compte')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGES', 'Charges'), ('PRODUITS', 'Produits'), ('TRESORERIE', 'Trésorerie')], max_length=20, verbose_name='Catégorie')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde actuel')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes', to='accounting.comptecomptable', verbose_name='Compte parent')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_comptables', to='establishments.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'db_table': 'accounting_compte_comptable',
                'ordering': ['numero_compte'],
                'unique_together': {('etablissement', 'numero_compte')},
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('numero_depense', models.CharField(max_length=50, unique=True, verbose_name='Numéro de dépense')),
                ('categorie', models.CharField(choices=[('SALAIRES', 'Salaires et charges'), ('FOURNITURES', 'Fournitures et matériel'), ('LOYER', 'Loyer et charges locatives'), ('ELECTRICITE', 'Électricité'), ('EAU', 'Eau'), ('INTERNET', 'Internet et télécommunications'), ('ENTRETIEN', 'Entretien et réparations'), ('ASSURANCES', 'Assurances'), ('TAXES', 'Taxes et impôts'), ('TRANSPORT', 'Transport'), ('MARKETING', 'Marketing et publicité'), ('FORMATION', 'Formation du personnel'), ('AUTRES', 'Autres dépenses')], max_length=20, verbose_name='Catégorie')),
                ('date_depense', models.DateField(default=django.utils.timezone.now, verbose_name='Date de dépense')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('description', models.TextField(verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('mode_paiement', models.CharField(max_length=50, verbose_name='Mode de paiement')),
                ('numero_piece', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de pièce justificative')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='accounting/depenses/%Y/%m/', verbose_name='Pièce justificative')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='establishments.etablissement', verbose_name='Établissement')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'accounting_depense',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_cloture', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_comptables', to='establishments.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'db_table': 'accounting_exercice_comptable',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPrevisionnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant_previsionnel', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant prévisionnel')),
                ('montant_realise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant réalisé')),
                ('type_budget', models.CharField(choices=[('RECETTES', 'Recettes'), ('DEPENSES', 'Dépenses')], max_length=20, verbose_name='Type de budget')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='establishments.etablissement', verbose_name='Établissement')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.exercicecomptable', verbose_name='Exercice comptable')),
            ],
            options={
                'verbose_name': 'Budget prévisionnel',
                'verbose_name_plural': 'Budgets prévisionnels',
                'db_table': 'accounting_budget_previsionnel',
                'ordering': ['exercice', 'type_budget'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('type_facture', models.CharField(choices=[('SCOLARITE', 'Frais de scolarité'), ('INSCRIPTION', "Frais d'inscription"), ('EXAMEN', "Frais d'examen"), ('FOURNITURES', 'Fournitures'), ('AUTRES', 'Autres')], max_length=20, verbose_name='Type de facture')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TTC')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant payé')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIELLE', 'Payée partiellement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('apprenant', models.ForeignKey(limit_choices_to={'role': 'APPRENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('emise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_emises', to=settings.AUTH_USER_MODEL, verbose_name='Émise par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='establishments.etablissement', verbose_name='Établissement')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='enrollment.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'accounting_facture',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_journal', models.CharField(choices=[('VENTES', 'Journal des ventes'), ('ACHATS', 'Journal des achats'), ('BANQUE', 'Journal de banque'), ('CAISSE', 'Journal de caisse'), ('OD', 'Opérations diverses')], max_length=20, verbose_name='Type de journal')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_comptables', to='establishments.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Journal comptable',
                'verbose_name_plural': 'Journaux comptables',
                'db_table': 'accounting_journal_comptable',
                'ordering': ['code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('numero_piece', models.CharField(max_length=50, verbose_name='Numéro de pièce')),
                ('date_ecriture', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'écriture")),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('reference_externe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence externe')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('LETTREE', 'Lettrée'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_comptables', to='establishments.etablissement', verbose_name='Établissement')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='payments.paiement', verbose_name='Paiement associé')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_comptables', to='accounting.facture', verbose_name='Facture associée')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='accounting.journalcomptable', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'accounting_ecriture_comptable',
                'ordering': ['-date_ecriture', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédit')),
                ('numero_ligne', models.IntegerField(default=1, verbose_name='Numéro de ligne')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='accounting.comptecomptable', verbose_name='Compte')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.ecriturecomptable', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'db_table': 'accounting_ligne_ecriture',
                'ordering': ['ecriture', 'numero_ligne'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('numero_ligne', models.IntegerField(default=1, verbose_name='Numéro de ligne')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'accounting_ligne_facture',
                'ordering': ['facture', 'numero_ligne'],
            },
        ),
    ]
