# Generated by Django 5.2.6 on 2025-10-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilapprenant',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establishments.anneeacademique'),
        ),
        migrations.AddField(
            model_name='profilapprenant',
            name='classe_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to='academic.classe'),
        ),
        migrations.AddField(
            model_name='profilapprenant',
            name='niveau_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.niveau'),
        ),
        migrations.AddField(
            model_name='profilapprenant',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'APPRENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_apprenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilenseignant',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='courses.matiere'),
        ),
        migrations.AddField(
            model_name='profilenseignant',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
