# Generated by Django 5.2.6 on 2025-10-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_classe_niveau_alter_filiere_departement'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilapprenant',
            name='classe_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to='academic.classe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='academic.departement', verbose_name='Département'),
        ),
    ]
