# Generated by Django 5.2.6 on 2025-10-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenseignant',
            name='est_chef_departement',
            field=models.BooleanField(default=False, verbose_name='Est chef de département'),
        ),
        migrations.AddField(
            model_name='profilenseignant',
            name='type_enseignant',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VACATAIRE', 'Vacataire')], default='VACATAIRE', max_length=20, verbose_name="Type d'enseignant"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departements_intervention',
            field=models.ManyToManyField(blank=True, related_name='enseignants_intervenants', to='academic.departement', verbose_name="Départements d'intervention"),
        ),
        migrations.AlterField(
            model_name='profilenseignant',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role__in': ['ENSEIGNANT', 'CHEF_DEPARTEMENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL),
        ),
    ]
