# Generated by Django 5.2.6 on 2025-11-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilenseignant_est_chef_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('ADMIN', "Administrateur d'établissement"), ('COMPTABLE', 'Comptable'), ('CHEF_DEPARTEMENT', 'Chef de département'), ('ENSEIGNANT', 'Enseignant'), ('APPRENANT', 'Apprenant')], default='APPRENANT', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfilComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employe', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('specialisation', models.CharField(blank=True, help_text='Ex: Comptabilité générale, Trésorerie, etc.', max_length=100, null=True)),
                ('certifications', models.TextField(blank=True, help_text='Certifications professionnelles (une par ligne)', null=True)),
                ('peut_valider_paiements', models.BooleanField(default=True, verbose_name='Peut valider les paiements')),
                ('peut_generer_factures', models.BooleanField(default=True, verbose_name='Peut générer les factures')),
                ('peut_voir_rapports_financiers', models.BooleanField(default=True, verbose_name='Peut consulter les rapports financiers')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'COMPTABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_comptable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil comptable',
                'verbose_name_plural': 'Profils comptables',
                'db_table': 'comptes_profil_comptable',
            },
        ),
    ]
