# Generated by Django 5.2.6 on 2025-10-03 18:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_cours', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('EVALUATION', 'Évaluation'), ('RATTRAPAGE', 'Rattrapage')], default='CM', max_length=20, verbose_name='Type de cours')),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('REPORTE', 'Reporté')], default='PROGRAMME', max_length=20, verbose_name='Statut')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('heure_debut_prevue', models.TimeField(verbose_name='Heure de début prévue')),
                ('heure_fin_prevue', models.TimeField(verbose_name='Heure de fin prévue')),
                ('date_effective', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('heure_debut_effective', models.TimeField(blank=True, null=True)),
                ('heure_fin_effective', models.TimeField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Objectifs')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu abordé')),
                ('cours_en_ligne', models.BooleanField(default=False, verbose_name='Cours en ligne')),
                ('url_streaming', models.URLField(blank=True, null=True, verbose_name='URL streaming')),
                ('presence_prise', models.BooleanField(default=False, verbose_name='Présence prise')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.classe', verbose_name='Classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('periode_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.periodeacademique', verbose_name='Période académique')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='establishments.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'courses_cours',
                'ordering': ['-date_prevue', '-heure_debut_prevue'],
            },
        ),
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('travail_fait', models.TextField(verbose_name='Travail fait en classe')),
                ('travail_donne', models.TextField(blank=True, null=True, verbose_name='Travail donné aux étudiants')),
                ('date_travail_pour', models.DateField(blank=True, null=True, verbose_name='Travail pour le')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('rempli_par', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rempli par')),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cahier_texte', to='courses.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Cahier de texte',
                'verbose_name_plural': 'Cahiers de texte',
                'db_table': 'courses_cahier_texte',
                'ordering': ['-cours__date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('semaine_debut', models.DateField(verbose_name='Début de semaine')),
                ('semaine_fin', models.DateField(verbose_name='Fin de semaine')),
                ('publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('actuel', models.BooleanField(default=False, verbose_name='Actuel')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='academic.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('periode_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='academic.periodeacademique', verbose_name='Période académique')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'db_table': 'courses_emploi_du_temps',
                'ordering': ['-semaine_debut'],
            },
        ),
        migrations.CreateModel(
            name='CreneauEmploiDuTemps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')], verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_edt', to='courses.cours', verbose_name='Cours')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='courses.emploidutemps', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': 'Créneau emploi du temps',
                'verbose_name_plural': 'Créneaux emploi du temps',
                'db_table': 'courses_creneau_emploi_du_temps',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('heures_cours_magistral', models.IntegerField(default=0, verbose_name='Heures CM')),
                ('heures_travaux_diriges', models.IntegerField(default=0, verbose_name='Heures TD')),
                ('heures_travaux_pratiques', models.IntegerField(default=0, verbose_name='Heures TP')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10)], verbose_name='Coefficient')),
                ('credits_ects', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Crédits ECTS')),
                ('couleur', models.CharField(default='#3498db', max_length=7, verbose_name='Couleur')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('enseignant_responsable', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant responsable')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academic.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'db_table': 'courses_matiere',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='courses.matiere', verbose_name='Matière'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('coordinateur', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_coordonnes', to=settings.AUTH_USER_MODEL, verbose_name='Coordinateur')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academic.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'courses_module',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='courses.module', verbose_name='Module (optionnel)'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'Retard'), ('EXCUSED', 'Absent excusé'), ('JUSTIFIED', 'Absence justifiée')], default='PRESENT', max_length=20, verbose_name='Statut')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('motif_absence', models.TextField(blank=True, null=True, verbose_name="Motif d'absence")),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='presences/justifications/', verbose_name='Document justificatif')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes_enseignant', models.TextField(blank=True, null=True, verbose_name="Notes de l'enseignant")),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='courses.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'courses_presence',
                'ordering': ['cours', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_ressource', models.CharField(choices=[('PDF', 'Document PDF'), ('DOC', 'Document Word'), ('PPT', 'Présentation PowerPoint'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('LINK', 'Lien web'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de ressource')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources_cours/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('telechargeable', models.BooleanField(default=True, verbose_name='Téléchargeable')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('disponible_a_partir_de', models.DateTimeField(blank=True, null=True, verbose_name='Disponible à partir de')),
                ('disponible_jusqua', models.DateTimeField(blank=True, null=True, verbose_name="Disponible jusqu'à")),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('nombre_vues', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='courses.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'db_table': 'courses_ressource',
                'ordering': ['cours', 'titre'],
            },
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['date_prevue', 'classe'], name='courses_cou_date_pr_b46dad_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['enseignant', 'date_prevue'], name='courses_cou_enseign_96eb43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('niveau', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('niveau', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('cours', 'etudiant')},
        ),
    ]
