# Generated by Django 5.2.6 on 2025-09-24 23:20

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('capacite_maximale', models.IntegerField(blank=True, null=True, verbose_name='Capacité maximale (par classe)')),
                ('effectif_actuel', models.IntegerField(default=0, verbose_name='Effectif actuel')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'academique_classe',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('bureau', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bureau')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'academique_departement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duree_annees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Durée (années)')),
                ('nom_diplome', models.CharField(max_length=200, verbose_name='Nom du diplôme')),
                ('type_filiere', models.CharField(choices=[('GENERAL', 'Enseignement général'), ('TECHNIQUE', 'Enseignement technique'), ('PROFESSIONNEL', 'Formation professionnelle'), ('UNIVERSITAIRE', 'Enseignement universitaire'), ('CONTINUE', 'Formation continue')], max_length=20, verbose_name='Type de filière')),
                ('prerequis', models.TextField(blank=True, null=True, verbose_name='Prérequis')),
                ('frais_scolarite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de scolarité')),
                ('capacite_maximale', models.IntegerField(blank=True, null=True, verbose_name='Capacité maximale (pour toute la filière)')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'academique_filiere',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('frais_scolarite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de scolarité (si différent de la filière)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'db_table': 'academique_niveau',
                'ordering': ['filiere', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeAcademique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('type_periode', models.CharField(choices=[('SEMESTRE', 'Semestre'), ('TRIMESTRE', 'Trimestre'), ('QUADRIMESTRE', 'Quadrimestre')], max_length=20, verbose_name='Type de période')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_limite_inscription', models.DateField(blank=True, null=True, verbose_name="Limite d'inscription")),
                ('date_debut_examens', models.DateField(blank=True, null=True, verbose_name='Début des examens')),
                ('date_fin_examens', models.DateField(blank=True, null=True, verbose_name='Fin des examens')),
                ('date_publication_resultats', models.DateField(blank=True, null=True, verbose_name='Publication des résultats')),
                ('est_courante', models.BooleanField(default=False, verbose_name='Période courante')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Période académique',
                'verbose_name_plural': 'Périodes académiques',
                'db_table': 'academique_periode',
                'ordering': ['annee_academique', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('objectifs', models.TextField(verbose_name='Objectifs pédagogiques')),
                ('competences', models.TextField(verbose_name='Compétences à acquérir')),
                ('debouches', models.TextField(blank=True, null=True, verbose_name='Débouchés professionnels')),
                ('credits_totaux', models.IntegerField(blank=True, null=True, verbose_name='Total des crédits')),
                ('date_derniere_revision', models.DateField(verbose_name='Dernière révision')),
                ('date_approbation', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'academique_programme',
            },
        ),
    ]
