# Generated by Django 5.2.6 on 2025-10-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='classe',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to=settings.AUTH_USER_MODEL, verbose_name='Professeur principal'),
        ),
        migrations.AddField(
            model_name='classe',
            name='salle_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establishments.salle', verbose_name='Salle principale'),
        ),
        migrations.AddField(
            model_name='departement',
            name='chef',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CHEF_DEPARTEMENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Chef de département'),
        ),
        migrations.AddField(
            model_name='departement',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academic.departement', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='academic.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.niveau', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='periodeacademique',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='periodeacademique',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishments.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='programme',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='programme',
            name='filiere',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='academic.filiere', verbose_name='Filière'),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('etablissement', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('etablissement', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('filiere', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('etablissement', 'annee_academique', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='periodeacademique',
            unique_together={('etablissement', 'annee_academique', 'code')},
        ),
    ]
