# Generated by Django 5.2.6 on 2025-09-27 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inscription',
            name='enrollment__etudian_110f9c_idx',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='etudiant',
            new_name='apprenant',
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['apprenant', 'statut'], name='enrollment__apprena_8178b7_idx'),
        ),
    ]
