# Generated by Django 5.2.6 on 2025-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='token_inscription',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name="Token d'inscription"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='token_inscription_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration du token"),
        ),
    ]
