# Generated by Django 5.2.6 on 2025-11-03 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_candidature_token_inscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='apprenant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'APPRENANT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant'),
        ),
    ]
